/// Flutter icons Myicon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Myicon
///      fonts:
///       - asset: fonts/Myicon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Myicon {
  Myicon._();

  static const _kFontFam = 'Myicon';
  static const String? _kFontPkg = null;

  static const IconData water_percent__1_ = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weather_sunset_up = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weather_sunset_down = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_1 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
